source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'RxMidi_Example' do
  use_frameworks!
  pod "RxMidi", :path => "../"
end

target 'RxMidi_Tests' do
  use_frameworks!
  pod "RxMidi", :path => "../"

  pod 'Quick', '~> 0.8'
  pod 'Nimble'
end
